### ISSUE TITLE
前两名咋能高那么多呢

### ISSUE THREAD

**Issue by sxpro** [littlewhitesea/NTIRE2021_compressed_video_enhancement#1]
。。。

**Comment by littlewhitesea** [comment]
确实有点高的离谱，希望比赛结束后能详细介绍一下他们的工作

**Comment by splinter21** [comment]
诶，比赛结果就出来了吗？前两名是说哪个哇？

**Comment by sxpro** [comment]
好像看到了splinter23的回复，想问下是不是用了basicVSR

**Comment by sxpro** [comment]
好像看到了 @splinter23  的回复，想问下是不是用了basicVSR

**Comment by suke27** [comment]
问下本方案是基于单张图的么, Track3_release_test_data 哪里能获取到

**Comment by littlewhitesea** [comment]
这个方案的输入是连续五帧图像。所有的比赛数据和其他的比赛方案可以访问https://github.com/RenYang-home/NTIRE21_VEnh.
