### ISSUE TITLE
如何生成测试数据

### ISSUE THREAD

**Issue by suke27** [littlewhitesea/NTIRE2021_compressed_video_enhancement#2]
请问下, NTIRE video quality enhancement Track3 200 kbps 码率压缩有固定的工具或脚本么? 还是直接用ffmpeg 压缩?

**Comment by littlewhitesea** [comment]
你好，详细的压缩工具以及操作步骤可以访问https://github.com/RenYang-home/NTIRE21_VEnh, 上面介绍得非常清楚。
